name: "Build image"
inputs:
  distro:
    required: true
  image_name:
    required: true
  quay_username:
    required: true
  quay_password:
    required: true
runs:
  using: "composite"
  steps:
  - name: check cache for previous image builds
    id: imagefiles
    uses: actions/cache@v3
    with:
      path: make_ci_image.sh
      key: ${{ github.ref_name }}-${{ inputs.distro }}-${{ hashfiles('make_ci_image.sh', 'pybuild.sh', '.github/actions/make-ci-image/action.yml') }}
  - name: build image
    if: (steps.imagefiles.outputs.cache-hit != 'true') || (github.event_name == 'schedule')
    run: ./make_ci_image.sh ${{ inputs.distro }}
    shell: bash
    env:
      image_name: ${{ inputs.image_name }}
  - name: login to quay.io
    if: (steps.imagefiles.outputs.cache-hit != 'true') || (github.event_name == 'schedule')
    run: buildah login -u="${{ inputs.quay_username }}" -p="${{ inputs.quay_password }}" quay.io
    shell: bash
  - name: publish image to quay.io
    if: (steps.imagefiles.outputs.cache-hit != 'true') || (github.event_name == 'schedule')
    run: buildah push ${{ inputs.image_name }}
    shell: bash
