name: CI

on:
  push:
    branches:
    - main
    paths:
    - 'pybuild.sh'
    - 'make_ci_image.sh'
    - '.github/workflows/ci.yml'
    - '.github/actions/preflight/action.yml'
    - '.github/actions/make-ci-image/action.yml'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - 'pybuild.sh'
    - 'make_ci_image.sh'
    - '.github/workflows/ci.yml'
    - '.github/actions/preflight/action.yml'
    - '.github/actions/make-ci-image/action.yml'
  schedule:
    - cron: "23 2 * * 6"

env:
  image_base: 'quay.io/km6g-ci-images/python'

jobs:
  preflight:
    runs-on: ubuntu-22.04
    outputs:
      need_image: ${{ steps.preflight.outputs.need_image }}
      image_tag: ${{ steps.preflight.outputs.image_tag }}
      # workaround to make image_base available in jobs
      image_base: ${{ env.image_base }}
    steps:
    - uses: actions/checkout@v3
    - id: preflight
      uses: ./.github/actions/preflight
  image:
    runs-on: ubuntu-22.04
    needs:
    - preflight
    strategy:
      matrix:
        distro: [bullseye]
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/make-ci-image
      if: needs.preflight.outputs.need_image == 'true'
      with:
        distro: ${{ matrix.distro }}
        image_name: ${{ needs.preflight.outputs.image_base }}:${{ matrix.distro }}-${{ needs.preflight.outputs.image_tag }}
        quay_username: ${{ secrets.QUAY_BOT_NAME }}
        quay_password: ${{ secrets.QUAY_BOT_PASSWORD }}
