name: CI

on:
  push:
    branches:
    - main
    paths:
    - 'workflow-support/make_ci_image.sh'
    - 'workflow-support/pybuild.sh'
    - '.github/workflows/ci.yml'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - 'workflow-support/make_ci_image.sh'
    - 'workflow-support/pybuild.sh'
    - '.github/workflows/ci.yml'
  schedule:
    - cron: "35 4 * * 5"

jobs:
  ci-image:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        distro: [bullseye]
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@main
      with:
        base_image_registry: docker.io
        base_image_registry_account: library
        base_image: debian:${{ matrix.distro }}
    - uses: actions/checkout@v3
    - id: preflight
      uses: kpfleming/composite-actions/ci-preflight@main
      with:
        files_hash: ${{ hashfiles('workflow-support/make_ci_image.sh', 'workflow-support/pybuild.sh') }}
        base_image_hash: ${{ steps.details.outputs.base_image_hash }}
    - id: make-ci-image
      uses: kpfleming/composite-actions/make-ci-image@main
      if: steps.preflight.outputs.need_image == 'true'
      with:
        base_image: ${{ steps.details.outputs.base_image }}
        image_name: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/python:${{ matrix.distro }}-${{ steps.preflight.outputs.image_tag }}
        image_registry: ${{ steps.details.outputs.image_registry }}
        registry_username: ${{ secrets.QUAY_BOT_NAME }}
        registry_password: ${{ secrets.QUAY_BOT_PASSWORD }}
