name: CI

on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
  schedule:
    - cron: "35 4 * * 5"

jobs:
  ci-image:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        distro: [bookworm]
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@v2
      with:
        base_image_registry: docker.io
        base_image_registry_account: library
        base_image: debian:${{ matrix.distro }}
    - uses: actions/checkout@v4
    - id: preflight
      uses: kpfleming/composite-actions/ci-preflight@v2
      with:
        ci_paths: workflow-support/ci_paths.yml
        files_hash: ${{ hashfiles('workflow-support/make_ci_image.sh', '.github/workflows/hatch-config.toml') }}
        base_image_hash: ${{ steps.details.outputs.base_image_hash }}
    - id: make-ci-image
      uses: kpfleming/composite-actions/make-ci-image@v2
      if: steps.preflight.outputs.need_image == 'true'
      with:
        base_image: ${{ steps.details.outputs.base_image }}
        image_name: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/python:v3-${{ matrix.distro }}-${{ steps.preflight.outputs.image_tag }}
        image_cache_key: ${{ steps.preflight.outputs.image_cache_key }}
        image_registry: ${{ steps.details.outputs.image_registry }}
        registry_username: ${{ secrets.QUAY_BOT_NAME }}
        registry_password: ${{ secrets.QUAY_BOT_PASSWORD }}
