name: CI

on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
  schedule:
    - cron: "35 4 * * 5"
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  ci-image:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        distro: [trixie]
    steps:
      - id: details
        uses: kpfleming/composite-actions/image-details@74c01bb4d399a98545e8cdc5826d832b7917ac6b # v3.1.0
        with:
          base_image_registry: docker.io
          base_image_registry_account: library
          base_image: debian:${{ matrix.distro }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - id: preflight
        uses: kpfleming/composite-actions/ci-preflight@74c01bb4d399a98545e8cdc5826d832b7917ac6b # v3.1.0
        with:
          ci_paths: workflow-support/ci_paths.yml
          files_hash: ${{ hashfiles('workflow-support/make_ci_image.sh', '.github/workflows/hatch-config.toml', '.github/workflows/ci.yml') }}
          base_image_hash: ${{ steps.details.outputs.base_image_hash }}

      - id: make-ci-image
        uses: kpfleming/composite-actions/make-ci-image@74c01bb4d399a98545e8cdc5826d832b7917ac6b # v3.1.0
        if: steps.preflight.outputs.need_image == 'true' || github.event_name == 'workflow_dispatch'
        with:
          base_image: ${{ steps.details.outputs.base_image }}
          image_name: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/python:v4-${{ matrix.distro }}-${{ steps.preflight.outputs.image_tag }}
          image_cache_key: ${{ steps.preflight.outputs.image_cache_key }}
          image_registry: ${{ steps.details.outputs.image_registry }}
          registry_username: ${{ vars.FORGE_BOT_NAME }}
          registry_password: ${{ secrets.FORGE_API_TOKEN }}
