name: Delete PR Image

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  clean-image:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        distro: [bookworm]
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@v3
    - uses: kpfleming/composite-actions/delete-pr-image@v3
      with:
        image_registry: ${{ steps.details.outputs.image_registry }}
        registry_account: ${{ steps.details.outputs.registry_account }}
        registry_token: ${{ secrets.FORGE_API_TOKEN }}
        repo_name: python
        tag_prefix: v4-${{ matrix.distro }}-
